typedef enum{KEY_STATE_NONE, KEY_STATE_PRESS, KEY_STATE_PRESS_HOLD, KEY_STATE_RELEASE} KeyState; 

typedef enum{KEY_ID_ESC, KEY_ID_F1, KEY_ID_F2, KEY_ID_F3, KEY_ID_F4, KEY_ID_F5, KEY_ID_F6, KEY_ID_F7, KEY_ID_F8, KEY_ID_F9, KEY_ID_F10, KEY_ID_F11, KEY_ID_F12, KEY_ID_PRTSC, KEY_ID_DELETE, KEY_ID_PO,
			KEY_ID_TILDE, KEY_ID_NUM_1, KEY_ID_NUM_2, KEY_ID_NUM_3, KEY_ID_NUM_4, KEY_ID_NUM_5, KEY_ID_NUM_6, KEY_ID_NUM_7, KEY_ID_NUM_8, KEY_ID_NUM_9, KEY_ID_NUM_0, KEY_ID_NUM_MINUS, KEY_ID_NUM_EQ, KEY_ID_NUM_BACKSP,
			KEY_ID_TAP, KEY_ID_Q, KEY_ID_W, KEY_ID_E, KEY_ID_R, KEY_ID_T, KEY_ID_Y, KEY_ID_U, KEY_ID_I,KEY_ID_O, KEY_ID_P, KEY_ID_OBRACKET, KEY_ID_CBRACKET, KEY_ID_BACKSLASH,
			KEY_ID_CAPS, KEY_ID_A, KEY_ID_S, KEY_ID_D,KEY_ID_F, KEY_ID_G, KEY_ID_H, KEY_ID_J, KEY_ID_K, KEY_ID_L, KEY_ID_SEMI, KEY_ID_QUOTE, KEY_ID_ENTER,
			KEY_ID_LSHIFT, KEY_ID_Z, KEY_ID_X, KEY_ID_C, KEY_ID_V, KEY_ID_B, KEY_ID_N, KEY_ID_M, KEY_ID_COMMA, KEY_ID_DOT, KEY_ID_SLASH, KEY_ID_RSHIFT,
			KEY_ID_CTRL, KEY_ID_NONE, KEY_ID_WINDOW, KEY_ID_ALT, KEY_ID_SPACE, KEY_ID_KOEN, KEY_ID_OTHERCHAR, KEY_ID_DIREC_UPDOWN,KEY_ID_DIREC_LEFT, KEY_ID_DIREC_RIGHT} KeyId;